### ISSUE TITLE
deprecated arguments with dplyr::across(...)

### ISSUE THREAD

**Issue by csjalbert** [commfish/GCLr#10]
Just a reminder to check for deprecated arguments in our functions whenever we have time. 
For example, across(), in the alt species function and anywhere else.

``There was 1 warning in `dplyr::mutate()`.
ℹ In argument: `dplyr::across(...)`.
Caused by warning:
! The `...` argument of `across()` is deprecated as of dplyr 1.1.0.
Supply arguments directly to `.fns` through an anonymous function instead.

  # Previously
  across(a:b, mean, na.rm = TRUE)

  # Now
  across(a:b, \(x) mean(x, na.rm = TRUE))` `

**Comment by awbarclay** [comment]
Function using dplyr::across  ... argument have been fixed

**Comment by csjalbert** [comment]
closing this issue as it appears fixed for all functions.
