### ISSUE TITLE
individual PCA function

### ISSUE THREAD

**Issue by krshedd** [commfish/GCLr#15]
We don't have one, but we should! I think Liz has some good, recent examples from her Pink Salmon range expansion analyses.

**Comment by boppingshoe** [comment]
We went over some PCA examples and ADMIXTURE stuff today at the workshop. Maybe we can try it on Liz's Pink sample after I get back. It might be helpful. I donno

Bobby Hsu
Biometrician II
(907) 267-2140
***@***.******@***.***>

From: Kyle Shedd ***@***.***>
Sent: Thursday, July 13, 2023 2:53 PM
To: commfish/GCLr ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [commfish/GCLr] individual PCA function (Issue #15)


CAUTION: This email originated from outside the State of Alaska mail system. Do not click links or open attachments unless you recognize the sender and know the content is safe.

We don't have one, but we should! I think Liz has some good, recent examples from her Pink Salmon range expansion analyses.

-

**Comment by awbarclay** [comment]
individual PCA function and plotting function have been added to GCLr 0.7.0
