### ISSUE TITLE
loki2R_gaps creates it's own LocusControl

### ISSUE THREAD

**Issue by awbarclay** [commfish/GCLr#16]
loki2r_gaps() creates it's own LocusControl object using the gaps conversion table in loki.   Then, it assigns LocusControl to the workspace. This is inconsistent with loki2r(), where it requires a LocusControl object to be made ahead of time using create_locuscontrol(). Should the create_locuscontrol function be updated to convert to gaps alleles if(markersuite == "GAPS_Chinook_uSATs"), and then update loki2r_gaps() with a LocusCtl argument and remove the code that creates and a LocusControl and assigns to workspace? Let's discuss at 7/14/23 R meeting.

**Comment by krshedd** [comment]
Unrelated, this function still creates "old-style" GCL objects (`LocusControl` as a 6-part list and the `.gcl` objects as 4-part list).

**Comment by awbarclay** [comment]
We decided to keep the `LocusControl` code in this function. The function has been updated to produce the tidy .gcl and `LocusControl`objects.
