### ISSUE TITLE
post_prior_diff_allele_freq() overhaul

### ISSUE THREAD

**Issue by csjalbert** [commfish/GCLr#20]
post_prior_diff_allele_freq() seemed not updated

_Originally posted by @boppingshoe in https://github.com/commfish/GCLr/issues/4#issuecomment-1654489090_
            
We should convert this to tidy and add spaces so us mere mortals can read it.

**Comment by awbarclay** [comment]
I will update this function and document, I'm the only one that has used it.  This isn't something that will get used very often, or ever...

**Comment by awbarclay** [comment]
This function is now tidy.
