### ISSUE TITLE
check issues from old repo and fix anything that applies here?

### ISSUE THREAD

**Issue by csjalbert** [commfish/GCLr#21]
There are a number of outstanding issues in the old repo `https://github.com/krshedd/GCL-R-Scripts/issues`. Can everyone review the issues they submitted and see if they need to be carried over or if they can simply be closed? Some are very old so I suspect they do not apply anymore or are not necessary.

**Comment by krshedd** [comment]
I finished going through old issues in `krshedd/GCL-R-Scripts`, closed them, and opened new issues here in `commfish/GCLr` for ones that I thought were still relevant.
