### ISSUE TITLE
Either finish cleaning up `get_tissue_locations()` or remove if not needed

### ISSUE THREAD

**Issue by awbarclay** [commfish/GCLr#23]
`get_tissue_locations()` was written for lab staff to help them clean up storage maps, but I'm not sure if it will be used again in the future.  I added documentation and cleaned up the RJDBC database connection code, but did not add `@export` or run `devtools::document()`  

If @hahoyt  and Jodi think it's still needed, @csjalbert will finish cleaning it up and export/document the function.

**Comment by csjalbert** [comment]
The lab would like to keep this and have it maintained so that they can use it more regularly. I'll finalize and document as necessary.

**Comment by awbarclay** [comment]
This was fixed in October, closing issue.
