### ISSUE TITLE
update `var_comp` to tidy `.gcl` objects

### ISSUE THREAD

**Issue by krshedd** [commfish/GCLr#24]
`var_comp` still uses old-style, 4-part list `.gcl` objects

**Comment by awbarclay** [comment]
I can update this one.  The only thing this function needs .gcl objects for is to create a hierfstat file.  I have a function that creates a hireftat data object in R that can take the place of reading in a file and it's already updated for the tibble .gcl objects `GCLr::create_hierfstat_data()`.  Do you want the option to read in a hierfstat file or just call on `GCLr::create_hierfstat_data()` to create the object needed for computing variance components?

**Comment by krshedd** [comment]
Let's include an option to read in a FSTAT `.dat` file, but have the default behavior be to use `GCLr::create_hierfstat_data()`. Does that work for you?

**Comment by awbarclay** [comment]
That works for me!

**Comment by awbarclay** [comment]
This function has been updated to use tidy .gcl objects.  Other updates: runs in parallel, creates it's own `hierfstat` data object or reads in and converts FSTAT .dat file, returns a `tibble`
