### ISSUE TITLE
failure_rate fake plates broken

### ISSUE THREAD

**Issue by csjalbert** [commfish/GCLr#27]
@awbarclay , the 'fake plate ID' section of `failure_rate` does not work when there is more than 1 plate in the project (e.g., S231). You can only have a single T/F within `if`, so I propose adding `any()` to fix the error. However, is this what you intended? Do we want to overwrite all plates with `00000` or just NA plates?
 ```
 # Add in a fake plate ID if none exists. This is needed to plot failure rate by plate and locus
  if (any(is.na(unique(master.tbl$plate)))) {
    
    message("The .gcl objects supplies do not contain plate IDs. Assigning a fake plate ID ('00000') to all sillys.")
    
    master.tbl <- master.tbl %>% 
      dplyr::mutate(plate = "00000")
    
  }
```

If you only want to fill in NA plates, then I think we need a `ifelse` or `case_when` in the mutate statement.

**Comment by awbarclay** [comment]
@csjalbert, I added this for cases when `failure_rate()` is used on .gcls that are created with `base2gcl() `and do not have plate IDs. However, the way I wrote it, all plate IDs would be replaced with '0000' if one plate ID was NA, which is not what I intended.  I modified the code so now it only adds a fake plate ID where they are missing using `dplyr::case_when()`. Thanks for the` any()` suggestion!  I got this to work without an error, so I'm closing the issue.  However, this should be tested some more to make sure it works in all cases.  
```
if (any(is.na(master.tbl$plate))) {
    
    message("Some or all of the .gcl objects supplies do not contain plate IDs. Assigning a fake plate ID ('00000') where they are missing.")
    
    master.tbl <- master.tbl %>% 
      dplyr::mutate(plate = dplyr::case_when(is.na(plate)~"00000",
                                      TRUE~plate))

  }
```
