### ISSUE TITLE
object names snake_case??

### ISSUE THREAD

**Issue by csjalbert** [commfish/GCLr#28]
I don't want to make the change without discussion but are we interested in changing all of our output objects to snake_case?  I noticed a few functions output objects in CamelCase (e.g., `LocusControl`, `MissLoci`).

I'm sure there are more than those two and any changes will need to be done throughout all functions that use them.

**Comment by krshedd** [comment]
While I am partial to `snake_case`, I think it would be a lot of effort/pain to change `LocusControl` to `locus_control`. Not sure the juice is worth the squeeze on this one.

**Comment by awbarclay** [comment]
I agree, with @krshedd.  I think it's more important to get the package working than worry about object nomenclature.

**Comment by krshedd** [comment]
Sounds good, I'm going to close this for now then. We can re-open later if we are feeling super ambitious.
