### ISSUE TITLE
@awbarclay functions to document

### ISSUE THREAD

**Issue by csjalbert** [commfish/GCLr#3]
@awbarclay here is a list of functions that you're required to document. Let @awbarclay or @csjalbert know if you have issues or questions. Reply to this issue with any questions or relevant information.
- [x] base_eval_sample_sizes
- [x] combine_loci
- [x] confusion_matrix
- [x] create_hierfstat_data
- [x] create_locuscontrol
- [x] create_rubias_base_eval
- [x] extract_photo_data
- [x] get_asl_data
- [x] hierfstat_global_stats
- [x] loki_url
- [x] loki2r
- [x] loki2r_gaps
- [x] new2old_gcl
- [x] pairwise_fst
- [x] plot_baseline_eval
- [x] plot_color_tree
- [x] plot_confusion_matrix
- [x] plot_quick_tree
- [x] pool_collections
- [x] read_genepop_pwfst
- [x] run_rubias_base_eval
- [x] save_nexus_color_tree
- [x] summarize_LD
- [x] temporal_collections
- [x] test_LD

**Comment by awbarclay** [comment]
All of my assigned functions have been documented.

**Comment by csjalbert** [comment]
Thanks. Closing this issue as completed.
