### ISSUE TITLE
update rubias functions to deal with multiple chains

### ISSUE THREAD

**Issue by krshedd** [commfish/GCLr#31]
It doesn't seem like many people are running multiple chains within *rubias* like we used to for *BAYES*, but it would be nice to either update our functions or add new ones to allow for this. When looking over NOAA Auke Bay Lab methods, I noticed that they run 1 chain per `repunit` with `method = "MCMC"` to assess convergence with Gelmin-Rubin, then, if there is convergence among chains with MCMC, they run 1 chain with `method = "PB"` for the final results.

To fully implement this change I think we'd either need to update or create wrappers for:
- [ ] `run_rubias_mix` or possible wrapper function `run_rubias_mix_multichain`?
- [ ] `custom_comb_rubias_output`
- [ ] `stratified_estimator_rubias`

What do folks think? Is this worthwhile? If so, should we update our existing functions, or leave them along and create wrapper functions to handle multiple chains?

**Comment by boppingshoe** [comment]
Yes, I recommend that we add an option to run multiple chains. In an unlikely scenario if someone question, "how did you know that your estimates converged?" we wouldn't be able to defend ourselves with only 1 chain.

I suggest updating the functions. Seems to me it would take similar amount of work to create a wrapper.

Bobby Hsu
Biometrician II
(907) 267-2140
***@***.******@***.***>

From: Kyle Shedd ***@***.***>
Sent: Thursday, September 7, 2023 12:48 PM
To: commfish/GCLr ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [commfish/GCLr] update rubias functions to deal with multiple chains (Issue #31)


CAUTION: This email originated from outside the State of Alaska mail system. Do not click links or open attachments unless you recognize the sender and know the content is safe.

It doesn't seem like many people are running multiple chains within rubias like we used to for BAYES, but it would be nice to either update our functions or add new ones to allow for this. When looking over NOAA Auke Bay Lab methods, I noticed that they run 1 chain per repunit with method = "MCMC" to assess convergence with Gelmin-Rubin, then, if there is convergence among chains with MCMC, they run 1 chain with method = "PB" for the final results.

To fully implement this change I think we'd either need to update or create wrappers for:

  *   [ ] run_rubias_mix or possible wrapper function run_rubias_mix_multichain?
  *   [ ] custom_comb_rubias_output
  *   [ ] stratified_estimator_rubias

What do folks think? Is this worthwhile? If so, should we update our existing functions, or leave them along and create wrapper functions to handle multiple chains?

-

**Comment by boppingshoe** [comment]
Anyone working on this? Maybe I'll try to tackle this. adding an option in the functions to run multiple chains. I'll try to make it minimum disruptive

**Comment by awbarclay** [comment]
No one is working on this issue. That would be awesome if you could work on it!  Make sure you push any changes to the develop branch.  Let me know if you need an help or have questions. Thanks, @boppingshoe!

**Comment by boppingshoe** [comment]
@krshedd @awbarclay @csjalbert just a heads up that I'm going to start working on the multi-chain stuff for rubias. To minimize conflicts, please let me know if you make changes to `run_rubias_mix()`, `custom_comb_rubias_output()` , or `stratified_estimator_rubias()`.
Another issue, do we generally avoid importing other packages? I noticed, for example, when doing parallel computing, there's a script `%dopar% <- foreach::%dopar%`. Why not just import `%dopar%` from `foreach`? I can leave them as they are if we want to avoid importing. But I can make the change for these functions if nobody object.

**Comment by awbarclay** [comment]
@boppingshoe We did try importing packages, but we didn't see the benefit of importing them when we are calling on function namespaces (e.g. `foreach::`).  There was also something about how imported packages get treated as dependencies that was annoying, but I can't remember what. I did import the magrittr pipe because it gets used a lot.  I guess we could do the same with %dopar%, but it seems just as easy to assign it (`%dopar% <- foreach::%dopar%`) in functions where we use it.

**Comment by boppingshoe** [comment]
Do you know if the package needs to be imported for each function? Like you imported the magrittr pipe for some function, do I need to import it again for the functions I work on?

**Comment by awbarclay** [comment]
@boppingshoe the `magrittr` pipe is imported into the package so it is available to use in `GCLr` functions included in the package namespace or if you have the GCLr package loaded. Here's how I added the pipe to the package: `usethis::use_pipe(export = TRUE) `  
I'm not sure if the usethis package has a similar function for %dopar%.  Personally, I don't think it's a big deal to assign the %dopar% in each function that uses it. We're using namespaces for function so there's no need to import packages.

**Comment by boppingshoe** [comment]
hey @awbarclay @krshedd @csjalbert I just remembered what Keenan said during the GCLr meeting about creating new branches. I wonder if I should create a new branch for the multi-chain stuff I'm working on, or should I just push the changes to the dev branch?

**Comment by awbarclay** [comment]
@boppingshoe, I think that it would be a good idea to create a new branch for this.  @krshedd and @csjalbert, what do you think?

**Comment by krshedd** [comment]
@boppingshoe @awbarclay , that makes sense to me, make sure to branch off of `main` rather than `develop`

**Comment by csjalbert** [comment]
I agree sounds like a good idea.

**Comment by krshedd** [comment]
This was closed with pull request #58
