### ISSUE TITLE
@boppingshoe functions to document

### ISSUE THREAD

**Issue by csjalbert** [commfish/GCLr#4]
@boppingshoe here is a list of functions that you're required to edit. Let @awbarclay or @csjalbert know if you have issues or questions. Reply to this issue with any questions or relevant information.
- [x] bayes_indiv_assign_summary
- [x] bayes_input_copy_paste
- [x] bayes_output_copy_paste
- [x] compare_comps_between
- [x] custom_comb_bayes_output
- [x] custom_comb_rubias_output
- [ ] post_prior_diff_allele_freq
- [x] random_inits
- [x] save_objects
- [x] save_sillys
- [x] stratified_estimator_bayes
- [x] stratified_estimator_rubias
- [x] summarize_rubias_individual_assign

**Comment by boppingshoe** [comment]
test edit bayes_indiv_assign_summary. Seemed to work

**Comment by boppingshoe** [comment]
slowly ticking them off...

**Comment by boppingshoe** [comment]
post_prior_diff_allele_freq() seemed not updated

**Comment by boppingshoe** [comment]
I finished all the documentations except for post_prior_diff_allele_freq(). should I close this issue?

**Comment by csjalbert** [comment]
Thanks @boppingshoe , closing this as completed since @awbarclay is going to deal with 'post_prior_diff_allele_freq' in issue #20
