### ISSUE TITLE
qc_template issues

### ISSUE THREAD

**Issue by awbarclay** [commfish/GCLr#44]
@csjalbert, @tylerdann found an issues with the `qc_template` while running the S253 QC analysis

In the `summ_by_silly` chunk, the code doesn't take into account that some project sillys are not included in the QC.
`
summary_by_silly <- project_sillys_n %>%
   dplyr::left_join(failure_rate$silly_failure_rate, by = "silly") %>%
   dplyr::rename("Failure Rate" = fail) %>%
   dplyr::mutate("Total qc Fish" = qc_sillys_n %>% 
   dplyr::pull(n)) # This mutate causes an error if some sillys were not included in the QC.
`
@tylerdann also had a couple of suggestions for enhancing the script.  

- Round off significant digits to 3 in all tables.
- Arrange all tables with the numbers of interest at the top (e.g,, higher failure rates at top) 

@csjalbert, I can take care of the bug with the `summary_by_silly` chunk and make it so all tables produced using `qc_table()` have a maximum of 3 significant digits. The arrange enhancement can wait until after the QC meeting on 10/11/23.

**Comment by awbarclay** [comment]
@csjalbert, I fixed the `summary_by_silly` bug and added some code to `qc_table()` so numbers will only have 3 significant digits.

**Comment by awbarclay** [comment]
@csjalbert can we close this issue?

**Comment by csjalbert** [comment]
closing since fixed with commit 3027960
