### ISSUE TITLE
get_geno Add project information

### ISSUE THREAD

**Issue by tcbarkley1** [commfish/GCLr#46]
[S253_GenotypesReport_09252023-103600.xlsx](https://github.com/commfish/GCLr/files/12921562/S253_GenotypesReport_09252023-103600.xlsx)

Add toggle to get project success rates, success rates by plate, etc. See attached file for example.

**Comment by awbarclay** [comment]
I'll fix this issue before the next GCLr version

**Comment by awbarclay** [comment]
This has been added
