### ISSUE TITLE
@hahoyt functions to document

### ISSUE THREAD

**Issue by csjalbert** [commfish/GCLr#5]
@hahoyt here is a list of functions that you're required to edit. Let @awbarclay or @csjalbert know if you have issues or questions. Reply to this issue with any questions or relevant information.

- [x] dupcheck_within_silly
- [x] get_geno
- [x] get_gtseq_metadata
- [x] get_proj_geno_stats
- [x] get_tissue_data
- [x] get_tssue_locations
- [x] silly_n

**Comment by hahoyt** [comment]
Found my way here! Yay me!

**Comment by krshedd** [comment]
I needed `get_geno`, so I documented that one for @hahoyt.
