### ISSUE TITLE
qc_template needs additional directions

### ISSUE THREAD

**Issue by awbarclay** [commfish/GCLr#61]
The directions at the beginning of QC script do not say to shut down and restart RStudio after saving the script. Because of this, lab staff unfamiliar with R are getting error messages when they try to run the first code chunk.  Here are the current directions with my suggested addition in bold:

1) Add a title and your name to the top of the script.
2) Save this to the QC directory **and restart RStudio to set your working directory**. Recommended naming convention: "project#_QC.Rmd". Example: S200_QC.Rmd
3) Run this script in order, one code chunk at a time, or some functions will not provide accurate results. This is by design, as this script only hits LOKI once to save time.
4) Add your review notes to the file (in the relevant project or QC review section), prior to finalizing (i.e., saving)!

@csjalbert, do you have time to add this?  If not, I can do it sometime. 

Also, Jodi has written up step by step instructions for lab staff to follow when running the QC script.  Maybe we should create documentation for the qc_template and include Jodi's instructions? That way people can look at the documentation for detailed instructions.

**Comment by csjalbert** [comment]
@awbarclay , good idea. I fixed this in commit 7a51ba7. I am leaving this open as I did not incorporate Jodi's documentation but agree that we should.

**Comment by awbarclay** [comment]
@csjalbert, thanks for adding that! I can work on creating QC script documentation when I have time.

**Comment by awbarclay** [comment]
This issues was taken care of in the last package update.
