### ISSUE TITLE
CM072 Project is too big for QC r script?

### ISSUE THREAD

**Issue by Jodiestrada** [commfish/GCLr#67]
![image](https://github.com/commfish/GCLr/assets/151694269/a9874a72-cc5f-4959-993a-48fc0f13fa14)

I am trying to run the QC r script for the CM072 project (119 plates) and it has been pulling genotypes for over 40 minutes. Here's a pic in case something else is going weird- like user error. I was going to use this as a demo on Tuesday but clearly that is a bad choice.

**Comment by csjalbert** [comment]
@Jodiestrada, this function is working fine. That said, the project is large (11k+ fish), so it took a bit over an hour for me when connected to the VPN. Anyway, in terms of a live demo, you're correct, this is not a good project to show. Here are few ideas for your demo:

1. I saved the output, so can share the RData and you can fake it (i.e., not run that line of code but still have the outputs so you can continue with the script)
2. pull a random smaller project - `GCLr::loki2r_proj(project_name = "S261", username = username, password = .password)`
3. pull a single (smaller) silly from CM052 - `GCLr::loki2r_proj(sillyvec = "CMNBS23", username = username, password = .password)`

Happy to help with any of the choices.

**Comment by csjalbert** [comment]
Closing as this is working.
