### ISSUE TITLE
GCLr QC script searches for "wrong name"

### ISSUE THREAD

**Issue by Jodiestrada** [commfish/GCLr#69]
On line 419, the GCLr QC script for gtseq (it doesn't do this for chips) searches the Conflict Reports folder for ConcordanceReport but Loki file output for gtseq is Concordance so it breaks. It is easily fixed by adding "Report" to the file name but Kyle said to raise a flag when it happened again.

![image](https://github.com/commfish/GCLr/assets/151694269/b9d91d19-fcfe-4c25-84e9-bbe5c226f7df)

![image](https://github.com/commfish/GCLr/assets/151694269/643a371e-bf4d-4178-9e9f-8a55fe050b67)

can't be sure if the image uploaded, I can send it separately if it doesn't

**Comment by krshedd** [comment]
Hey @Jodiestrada 

Thanks for flagging this. I see 3 pretty easy solutions: 

1. have Eric/Keenan update the LOKI so the GT-seq QC bounce produces a file called “ConcordanceReport”, just like chips, or
2. we just chance the QC R script to `pattern = “Concordance”`. Would that work?
3. lab staff continue to rename files manually to "ConcordanceReport" (this one seems lame)

Kyle

**Comment by Jodiestrada** [comment]
I think the Concordance pattern (option 2) is just dandy. There shouldn't be any other csv's with that file name in the folder.

Thanks!
jodi

Jodi Estrada
Gene Conservation Lab Manager
333 Raspberry Rd
Anchorage, AK 99517
907-267-2249

**Comment by krshedd** [comment]
Sounds good @Jodiestrada, I'll go ahead and make that change! We'll let you know when it is ready for your re-install the `GCLr` package with this update!
