### ISSUE TITLE
"Simple" QC script for lab folk?

### ISSUE THREAD

**Issue by Jodiestrada** [commfish/GCLr#76]
Hi team! I got some feedback from a couple of the genotypers and they were wondering if there could be a very pared down, separate QC bounce script for the lab folk to use. They like to have genotype success rate by plate and would like the information in the pivot table (attached), if possible:
 
[qcscript.docx](https://github.com/commfish/GCLr/files/14594461/qcscript.docx)

**Comment by awbarclay** [comment]
@Jodiestrada, sure this could be a simple function that produces the pivot table and writes it out to an excel file.  Is that what you want, or do you want it to be a markdown like the QC script?

**Comment by Jodiestrada** [comment]
Hi Andy- never got that comment :( 

An excel file is just great, thank you!

**Comment by awbarclay** [comment]
@Jodiestrada, I totally forgot about this!  I'll work on a function when I have some free time. If this is something that you would like done before the fall rush, I can work on it sooner.

**Comment by Jodiestrada** [comment]
it would be nice for fall rush since we are about to start churning out projects but don't break your back, we'll be fine without it

**Comment by awbarclay** [comment]
Okay, I might have time today before my inseason data are ready for analysis. I may have some questions for you when I start working on it.

**Comment by awbarclay** [comment]
qc_bounce function has been added to version 0.7.0
