### ISSUE TITLE
Add precision and recall values for minimum threshold (default = 0.5) for each reporting group to output of IA_thresholds 

### ISSUE THREAD

**Issue by tylerdann** [commfish/GCLr#77]
It would be nice to return the precision and recall values for our minimum threshold value of 0.5 for reporting groups that don't meet our standard criteria (precision > 0.95 and recall > 0.8) to get a sense for how bad they are or how close they are to meeting criteria. As currently written results for groups that don't pass criteria don't appear in output of function. This could take the form of two additional columns to the resulting tibble: prec_at_min_threshold and rec_at_min_threshold or something similar.

**Comment by krshedd** [comment]
@tylerdann that information is already in the `rates` data, you can just filter that directly to get that information.

`rates %>%
dplyr::filter(level == 0.5`

note that tpr (true positive rate) = recall and pre = precision

**Comment by tylerdann** [comment]
Thanks
