### ISSUE TITLE
@tylerdann functions to document

### ISSUE THREAD

**Issue by csjalbert** [commfish/GCLr#8]
@tylerdann here is a list of functions that you're required to edit. Let @awbarclay or @csjalbert know if you have issues or questions. Reply to this issue with any questions or relevant information.
- [x] create_prior
- [x] load_sillys
- [x] mutichain_inits
- [x] old2new_gcl
- [x] old2new_locuscontrol
- [x] plot_sampn_by_locus
- [x] remove_dups
- [x] remove_ids
- [x] remove_ind_miss_loci
- [x] remove_na_indv
- [x] run_rubias_mix
- [x] sampn_by_locus

**Comment by awbarclay** [comment]
I added Tyler's documented functions for him. For some reason, he could not push to GitHub.
