### ISSUE TITLE
LOKI column names

### ISSUE THREAD

**Issue by csjalbert** [commfish/GCLr#9]
@krshedd mentioned using `janitor::clean_names()` to fix the headers that come out of LOKI (e.g., the tissue table function). They are mixed-case, have spaces, and are generally a pain to work with. What if we add an additional option (clean_names = T/F) that fixes them when LOKI data are pulled?  

Wi'll run into issues if we need to export a CSV for uploading back to LOKI, since the names will have changed. A solution would be to make a function that converts the cleaned names back to the required format. Is this worth following up on?

**Comment by awbarclay** [comment]
Can't people just run janitor::clean_names() after they pull the data from Loki?  I rather not add an option to clean the names in the function and then have to write another function to change the names back. It's a cool function though, I'm sure I'll use it now that I know about it.  Maybe we can discuss adding this option at our next R meeting.

**Comment by krshedd** [comment]
Ya, good point Andy. Seems like this ship has sailed on this one since there are a lot of other functions that depend on the names that come out of LOKI as is. I'm going to close this one unless anyone else feels strongly about it.
