### ISSUE TITLE
LOKI URL update

### ISSUE THREAD

**Issue by csjalbert** [commfish/GCLr#98]
Last nights LOKI database migration broke the existing connection, and the database URLs need replaced. I have the new connection but still waiting on test_db info from Eric. 

`Host: soaocip-ovpnc-scan.exa.sjcprod.oraclevcn.com;
Port: 1521;
Service Name: DFGGCLP.exa.sjcprod.oraclevcn.com`

**Comment by awbarclay** [comment]
All branches have been updated with the new url info.
